### ISSUE TITLE
Using custom pykeen dataset for ablation study

### ISSUE THREAD

**Issue by serenalotreck** [pykeen/benchmarking#29]
Hi All,

Great work on this paper and thanks for such a thorough repository!

I'd like to perform the same hyperparameter tuning for a model trained on my own dataset, which I've added to pykeen by following the [Extending the Datasets](https://pykeen.readthedocs.io/en/stable/extending/datasets.html) instructions in the PyKEEN docs for my local installation. I'm able to import my own dataset properly after doing this. My dataset is named `pickle`.

I was hoping that I could then just use the command

```
python ablation/search.py --dataset pickle
```

to run the hyperparameter search for my dataset, but it runs quickly (~30 seconds) and silently (no errors or print statements) without producing any output.

I took a look at the code to see if I was missing some other adaptation that I had to make in order to run it on a new dataset, but didn't see anything that looked like I needed to change it.

Wondering what I'm missing here?

**Comment by mberr** [comment]
Hi @serenalotreck ,

this repository contains the experimental results in [./ablation](https://github.com/pykeen/benchmarking/tree/master/ablation). The [`ablation/search.py`](https://github.com/pykeen/benchmarking/blob/6268854e3855cfcbf26ac5d3f9c6d139e59d50a4/ablation/search.py) only searches through the JSON files containing the experimental results.

To create such results with PyKEEN, take a look at the [Running HPO tutorial](https://pykeen.readthedocs.io/en/stable/tutorial/running_hpo.html).

**Comment by cthoyt** [comment]
I don't recall where we wrote it before, but the ablation study code isn't meant to be a feature that's extensible. Like Max said, anyone can roll their own with the HPO pipeline

**Comment by serenalotreck** [comment]
Ah that wasn't clear to me, thank you!
